id: IF483F9C9
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:25:53.598428
last_modified: 2023-02-10 00:25:53.598581
source_metadata:
  title: 'Asaṅga: Triśatikāyāḥ Prajñāpāramitāyāḥ Kārikāsaptatiḥ'
  language: bo
bases:
  1E07:
    base_file: 1E07.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
